name: Build
on: push

jobs:

  Linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        compiler: [g++, clang]
        build_type: [Debug, Release]
        include:
          - compiler: g++
            c_compiler: gcc-11
            cpp_compiler: g++-11
          - compiler: clang
            c_compiler: clang-11
            cpp_compiler: clang++-11
          - build_type: Debug
            output_name_postfix: Debug
            
    env:
      CC: ${{matrix.c_compiler}}
      CXX: ${{matrix.cpp_compiler}}
      
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install packages
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key 2>/dev/null | sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/focal llvm-toolchain-focal-11 main' -y
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install build-essential gcc-11 g++-11 clang-11 lcov valgrind
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 90
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 90
          sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-11 90  
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-11 90
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-11 90
          
      - name: Check versions
        run: |
          cmake --version
          ${{matrix.c_compiler}} --version
          ${{matrix.cpp_compiler}} --version
          gcov --version
          python --version
      - name: Build
        run: |
          mkdir Build
          cd Build
          cmake -DMOLTEN_ENABLE_COVERAGE=ON -DMOLTEN_ENABLE_VULKAN=OFF -DCMAKE_BUILD_TYPE=${{matrix.build_type}} ..
          cmake --build . --config ${{matrix.build_type}}
      - name: Test
        run: |
          cd Bin
          valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./MoltenCoreTests${{matrix.output_name_postfix}}
          valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./MoltenGraphicsTests${{matrix.output_name_postfix}}
          valgrind --leak-check=full --track-origins=yes --error-exitcode=1 ./MoltenEditorFrameworkTests${{matrix.output_name_postfix}}
      - uses: codecov/codecov-action@v3
        if: ${{ matrix.compiler == 'g++' && matrix.build_type == 'Debug' }}
        with:
          gcov: true